const { validationResult } = require('express-validator')

const validateRequest = (req, res, next) => {
  // Parse errors generated by express-validator
  const errors = validationResult(req)

  if (!errors.isEmpty()) {
    res.status(400).json(errors)
  } else next()
}

module.exports = validateRequest
